Repository FoundationDB/fdb-kubernetes-operator, pull requests merged in 2023-11, with the labels that each got.

#1868 Correct the version check for the locality based exclusions
  api/v1beta2/foundationdb_version.go
  api/v1beta2/foundationdb_version_test.go
  api/v1beta2/foundationdbcluster_types.go
  controllers/exclude_processes_test.go
  controllers/remove_process_groups_test.go
  docs/cluster_spec.md
  e2e/Makefile
Labels: bug

#1877 Make sure the set finalizer method actually set the finalizer
  e2e/fixtures/pods.go
  e2e/test_operator/operator_test.go
  e2e/test_operator_upgrades/operator_upgrades_test.go
Labels: bug

#1879 Make sure the e2e test suite only runs locality based e2e tests if the provided versions support it
  e2e/test_operator/operator_test.go
  e2e/test_operator_upgrades_variations/operator_upgrades_variations_test.go
Labels: bug

#1882 Allow to define creationTimestamp mock
  mock-kubernetes-client/client/client.go
  mock-kubernetes-client/client/client_test.go
Labels: enhancement

#1880 Make sure the exclusion is tried again
  e2e/test_operator/operator_test.go
Labels: bug

#1886 Ignore HA locality-based exclusion test if version doesn't support locality based exclusions
  e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
Labels: bug

#1881 Add check for plugin version upgrades
  kubectl-fdb/Readme.md
  kubectl-fdb/cmd/analyze_test.go
  kubectl-fdb/cmd/deprecation_test.go
  kubectl-fdb/cmd/plugin_version_checker.go
  kubectl-fdb/cmd/restart_test.go
  kubectl-fdb/cmd/root.go
  kubectl-fdb/cmd/root_test.go
  kubectl-fdb/cmd/suite_test.go
  kubectl-fdb/cmd/version_test.go
  kubectl-fdb/main.go
Labels: plugin

#1857 including processes using excluded server list
  controllers/remove_process_groups.go
  controllers/remove_process_groups_test.go
  e2e/test_operator/operator_test.go
  pkg/fdbadminclient/mock/admin_client_mock.go
Labels: bug
