Repository FoundationDB/fdb-kubernetes-operator, pull requests merged in 2023-03, with the labels that each got.

#1522 Complement ProcessRole and ProcessClass
  api/v1beta2/foundationdb_process_class.go
  api/v1beta2/foundationdb_status.go
  api/v1beta2/foundationdb_status_test.go
Labels: bug

#1521 Add Version Check to Redwood Experimental Storage Engine Type
  api/v1beta2/foundationdb_database_configuration.go
  api/v1beta2/foundationdb_version.go
  api/v1beta2/foundationdbcluster_types_test.go
  controllers/cluster_controller_test.go
Labels: bug

#1533 Add longer delay after kill command
  fdbclient/admin_client.go
Labels: bug

#1538 Fix upgrade logic for multiple storage server per Pod
  api/v1beta2/foundationdbcluster_types.go
  controllers/bounce_processes.go
  controllers/bounce_processes_test.go
Labels: bug

#1547 Make sure we always check the sidecar to get the most recent information about the updated ConfigMap
  controllers/add_services_test.go
  controllers/bounce_processes.go
  controllers/change_coordinators_test.go
  controllers/choose_removals_test.go
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/suite_test.go
  controllers/update_pod_config.go
  controllers/update_status.go
  controllers/update_status_test.go
  internal/configmap_helper.go
  internal/fdb_status_helper_test.go
  internal/foundationdb_status.go
  internal/foundationdb_status_test.go
  internal/locality/locality.go
  internal/locality/locality_test.go
  pkg/fdbadminclient/mock/admin_client_mock.go
Labels: bug

#1550 Ensure we call exclude only on missing processes
  fdbclient/admin_client.go
  fdbclient/admin_client_test.go
  fdbclient/common.go
  fdbclient/fdb_client.go
Labels: bug, technical-debt

#1560 Install checksum step for kubectl fdb plugin
  kubectl-fdb/Readme.md
Labels: documentation
