Repository FoundationDB/fdb-kubernetes-operator, pull requests merged in 2023-02, with the labels that each got.

#1510 Correct typo for replaceProcessGroup
  api/v1beta1/foundationdbcluster_types.go
  api/v1beta2/foundationdbcluster_types.go
  docs/cluster_spec.md
  kubectl-fdb/cmd/root.go
Labels: documentation

#1511 Initial round of documenting the upgrade process
  docs/manual/imgs/upgrade_mechanism.svg
  docs/manual/index.md
  docs/manual/technical_design.md
  docs/manual/upgrades.md
  kubectl-fdb/cmd/remove_process_group.go
Labels: documentation

#1516 fix CVE-2022-41723
  go.mod
  go.sum
Labels: dependencies

#1517 Remove the minimum uptime check in the replace incompatible connections subreconciler
  controllers/remove_incompatible_processes.go
Labels: technical-debt

#1524 Fix permission issue for log file writer
  setup/setup.go
  setup/setup_test.go
  setup/suite_test.go
Labels: bug
