Repository FoundationDB/fdb-kubernetes-operator, pull requests merged in 2023-05, with the labels that each got.

#1609 Fix the way the resources for storage processes are calculated in the e2e test framework
  e2e/fixtures/cluster_config.go
  e2e/fixtures/cluster_config_test.go
  e2e/fixtures/suite_test.go
Labels: bug

#1626 Make sure to only check exclusions if we have 1 active generation
  fdbclient/admin_client.go
  fdbclient/admin_client_test.go
Labels: bug

#1635 Define pr and nightly tests
  e2e/Makefile
  e2e/README.md
  e2e/test_operator/operator_test.go
  e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
  e2e/test_operator_upgrades/operator_upgrades_test.go
  e2e/test_operator_velocity/operator_velocity_test.go
  logs/.gitignore
Labels: enhancement

#1637 Remove the internal Pod map and use the controller runtime cache
  api/v1beta2/foundationdbcluster_types.go
  api/v1beta2/foundationdbcluster_types_test.go
  controllers/add_pods.go
  controllers/delete_pods_for_buggification.go
  controllers/generate_initial_cluster_file.go
  controllers/remove_incompatible_processes.go
  controllers/replace_failed_process_groups_test.go
  controllers/replace_misconfigured_process_groups.go
  controllers/suite_test.go
  controllers/update_labels.go
  controllers/update_pod_config.go
  controllers/update_pods.go
  controllers/update_pods_test.go
  controllers/update_sidecar_versions.go
  controllers/update_status.go
  controllers/update_status_test.go
  internal/pod_helper.go
  internal/replacements/replacements.go
  internal/replacements/replacements_test.go
  internal/replacements/suite_test.go
  pkg/podmanager/pod_lifecycle_manager.go
Labels: enhancement

#1641 Update e2e README.md
  e2e/README.md
Labels: documentation

#1642 Fix e2e docs typo
  e2e/README.md
Labels: documentation

#1643 Add the additional processes only once and not multiple times
  pkg/fdbadminclient/mock/admin_client_mock.go
  pkg/fdbadminclient/mock/admin_client_mock_test.go
Labels: technical-debt

#1608 Initial support for fault domains in CRD
  api/v1beta2/foundationdbcluster_types.go
  config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
  controllers/update_status.go
  controllers/update_status_test.go
  docs/cluster_spec.md
Labels: enhancement
