Repository FoundationDB/fdb-kubernetes-operator, pull requests merged in 2023-06, with the labels that each got.

#1587 Add MaxZonesWithUnavailablePods for the update process. Fixes #1444.
  api/v1beta2/foundationdbcluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
  controllers/update_pods.go
  controllers/update_pods_test.go
  docs/cluster_spec.md
  docs/manual/replacements_and_deletions.md
Labels: enhancement

#1664 Update customization.md
  docs/manual/customization.md
Labels: documentation

#1666 BugFix: init faultDomainsWithUnavailablePods before checking ProcessGroups updates
  controllers/update_pods.go
  controllers/update_pods_test.go
Labels: bug

#1630 Fix kind e2e tests.
  e2e/Makefile
  e2e/README.md
  e2e/fixtures/cluster_config.go
  e2e/fixtures/cluster_config_test.go
  e2e/fixtures/factory.go
  e2e/fixtures/fdb_cluster_specs.go
  e2e/fixtures/fdb_operator_client.go
  e2e/fixtures/options.go
  e2e/scripts/setup_e2e.sh
  e2e/scripts/start_kind_cluster.sh
Labels: enhancement

#1672 Make sure we update the sidecar images too for patch upgrades
  e2e/test_operator_upgrades/operator_upgrades_test.go
  internal/pod_models.go
  internal/pod_models_test.go
Labels: bug

#1669 Fixes issue #1640
  kubectl-fdb/cmd/k8s_client.go
  kubectl-fdb/cmd/k8s_client_test.go
  kubectl-fdb/cmd/restart.go
Labels: enhancement, plugin

#1681 Reduce the size of the process map by selecting only processes in the right DC
  controllers/update_status.go
Labels: technical-debt

#1688 Make sure we set the connection string if the status is cached
  controllers/change_coordinators.go
  controllers/cluster_controller.go
  controllers/update_status.go
  e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
Labels: bug

#1697 Fix panic in analyze command if cluster is not found
  kubectl-fdb/cmd/analyze.go
Labels: bug, plugin

#1706 Run kill command once without back off to reduce risk of multiple recoveries
  fdbclient/admin_client.go
Labels: technical-debt

#1705 Improve the logging for the cluster controller to make sure all fields are set
  controllers/add_pods.go
  controllers/add_pods_test.go
  controllers/add_process_groups.go
  controllers/add_process_groups_test.go
  controllers/add_pvcs.go
  controllers/add_pvcs_test.go
  controllers/add_services.go
  controllers/add_services_test.go
  controllers/backup_controller.go
  controllers/bounce_processes.go
  controllers/bounce_processes_test.go
  controllers/change_coordinators.go
  controllers/change_coordinators_test.go
  controllers/check_client_compatibility.go
  controllers/choose_removals.go
  controllers/choose_removals_test.go
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/controllers.go
  controllers/delete_pods_for_buggification.go
  controllers/delete_pods_for_buggification_test.go
  controllers/exclude_processes.go
  controllers/exclude_processes_test.go
  controllers/generate_initial_cluster_file.go
  controllers/maintenance_mode_checker.go
  controllers/maintenance_mode_checker_test.go
  controllers/remove_incompatible_processes.go
  controllers/remove_process_groups.go
  controllers/remove_process_groups_test.go
  controllers/remove_services.go
  controllers/replace_failed_process_groups.go
  controllers/replace_failed_process_groups_test.go
  controllers/replace_misconfigured_process_groups.go
  controllers/restore_controller.go
  controllers/suite_test.go
  controllers/update_backup_agents.go
  controllers/update_backup_status.go
  controllers/update_config_map.go
  controllers/update_database_configuration.go
  controllers/update_lock_configuration.go
  controllers/update_lock_configuration_test.go
  controllers/update_metadata.go
  controllers/update_metadata_test.go
  controllers/update_pod_config.go
  controllers/update_pod_config_test.go
  controllers/update_pods.go
  controllers/update_pods_test.go
  controllers/update_sidecar_versions.go
  controllers/update_status.go
  controllers/update_status_test.go
Labels: bug, technical-debt

#1632 Update taint feature design doc and user manual
  docs/design/node_taint_eviction.md
  docs/manual/replacements_and_deletions.md
Labels: documentation
