Repository FoundationDB/fdb-kubernetes-operator, pull requests merged in 2024-03, with the labels that each got.

#1957 Minor typo fix in mention of localities
  docs/manual/technical_design.md
Labels: documentation

#1956 Document issue with older fdb bindings and DNS support
  .gitignore
  docs/manual/operator_customization.md
Labels: documentation

#1961 Add the known limitation that the FDB cluster is only reachable from within Kubernetes
  README.md
Labels: documentation

#1968 Update the state of the helm charts
  README.md
  charts/fdb-operator/Chart.yaml
  charts/fdb-operator/templates/tests/test-connection.yaml
Labels: documentation

#1967 Initial changes for new maintenance mode integration
  api/v1beta2/foundationdbcluster_types.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
  controllers/bounce_processes.go
  controllers/change_coordinators.go
  controllers/cluster_controller.go
  controllers/maintenance_mode_checker.go
  controllers/maintenance_mode_checker_test.go
  controllers/suite_test.go
  controllers/update_database_configuration.go
  controllers/update_pods.go
  controllers/update_pods_test.go
  controllers/update_status.go
  controllers/update_status_test.go
  docs/cluster_spec.md
  docs/manual/operations.md
  e2e/fixtures/fdb_cluster.go
  e2e/fixtures/status.go
  e2e/test_operator/operator_test.go
  e2e/test_operator_ha_upgrades/operator_ha_upgrade_test.go
  fdbclient/admin_client.go
  internal/maintenance/maintenance.go
  internal/maintenance/maintenance_test.go
  internal/maintenance/suite_test.go
  pkg/fdbadminclient/admin_client.go
  pkg/fdbadminclient/mock/admin_client_mock.go
  setup/setup.go
Labels: enhancement

#1971 Add safety checks for inclusion and improve the exclusion check
  controllers/cluster_controller.go
  controllers/exclude_processes.go
  controllers/remove_process_groups.go
  controllers/remove_process_groups_test.go
  docs/manual/technical_design.md
  e2e/fixtures/fdb_operator_client.go
  internal/removals/remove.go
  pkg/fdbadminclient/mock/admin_client_mock.go
  pkg/fdbstatus/status_checks.go
  pkg/fdbstatus/status_checks_test.go
  setup/setup.go
Labels: enhancement

#1972 Correct version check for automatic tester process removal
  api/v1beta2/foundationdb_version.go
  api/v1beta2/foundationdb_version_test.go
  e2e/test_operator/operator_test.go
Labels: bug

#1975 Improve documentation
  README.md
  docs/compatibility.md
  docs/manual/customization.md
  docs/manual/debugging.md
  docs/manual/fault_domains.md
  docs/manual/getting_started.md
  docs/manual/operations.md
  docs/manual/operator_customization.md
  docs/manual/replacements_and_deletions.md
  docs/manual/resources.md
  docs/manual/scaling.md
  docs/manual/tls.md
  docs/manual/warnings.md
  e2e/README.md
Labels: documentation
