Repository FoundationDB/fdb-kubernetes-operator, pull requests merged in 2025-05, with the labels that each got.

#2273 Fix crash in findFoundationDBClusterForNode when in global mode
  controllers/cluster_controller.go
  controllers/cluster_controller_test.go
  controllers/suite_test.go
Labels: bug

#2281 Update the go version to 1.23.9
  .github/workflows/pull_request.yml
  .github/workflows/release.yaml
  Dockerfile
Labels: technical-debt

#2261 Add support management api
  api/v1beta2/foundationdb_process_address.go
  api/v1beta2/foundationdbcluster_types.go
  api/v1beta2/foundationdbcluster_types_test.go
  api/v1beta2/zz_generated.deepcopy.go
  config/crd/bases/apps.foundationdb.org_foundationdbclusters.yaml
  controllers/cluster_controller_test.go
  controllers/exclude_processes_test.go
  controllers/maintenance_mode_checker_test.go
  controllers/remove_process_groups.go
  controllers/remove_process_groups_test.go
  docs/cluster_spec.md
  e2e/fixtures/factory.go
  e2e/test_operator_plugin/operator_plugin_test.go
  e2e/test_operator_upgrades/operator_upgrades_test.go
  fdbclient/admin_client.go
  fdbclient/admin_client_test.go
  fdbclient/common.go
  fdbclient/fdb_client.go
  fdbclient/lock_client.go
  kubectl-fdb/cmd/k8s_client.go
  kubectl-fdb/cmd/recover_multi_region_cluster.go
  main.go
  mock-kubernetes-client/client/client.go
  pkg/fdbadminclient/admin_client.go
  pkg/fdbadminclient/mock/admin_client_mock.go
  pkg/fdbadminclient/mock/admin_client_mock_test.go
Labels: enhancement

#2283 Run the addPods reconciler before connecting to FDB in case we use DNS entries in the cluster file
  controllers/add_pods.go
  controllers/cluster_controller.go
  controllers/update_status.go
  e2e/test_operator/operator_test.go
Labels: bug
